### ISSUE TITLE
Payment method is temporary unavailable.

### ISSUE THREAD

**Issue by harked** [Paybear/paybear-php#1]
Hi, 

I've setup manual installation on this script on my local (using MAMP), but after I open up index.php on my browser, then click on 'Pay with Crypto' button, I get this below message 

"This payment method is temporarily unavailable. Please try again in a minute." 

any help would be appreciated?

![image](https://user-images.githubusercontent.com/5647602/44662282-e7000580-aa3f-11e8-8476-5af8a884b12d.png)

**Comment by xuchao-25824839** [comment]
you can check currencies.php and you're script , if response not had ['address'] , it can't be running, please follow this . added currencies.php (after Line 24 )
```php
$data['address'] = 'xxxxx'
$data['explorer_xxxx'] = 'xxxxx'
```
reflush web page ,done!

**Comment by harked** [comment]
HI @xuchao-25824839 thanks for your advice. But after doing what youve suggested. The error message still appear : 
"This payment method is temporarily unavailable. Please try again in a minute."

anyone can help?
